# 1.
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS
LEFT OUTER JOIN ANIMAL_INS
ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
WHERE ANIMAL_INS.ANIMAL_ID is NULL;

# 2.
# SELECT ANIMAL_ID, NAME
# FROM ANIMAL_OUTS
# WHERE ANIMAL_ID not in (SELECT ANIMAL_ID FROM ANIMAL_INS);