SELECT B.ANIMAL_ID, B.ANIMAL_TYPE, B.NAME
FROM ANIMAL_INS as A
JOIN ANIMAL_OUTS as B
ON A.ANIMAL_ID=B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE LIKE 'INTACT%' AND (B.SEX_UPON_OUTCOME LIKE 'SPAYED%' OR B.SEX_UPON_OUTCOME LIKE 'NEUTERED%')
ORDER BY B.ANIMAL_ID